### ISSUE TITLE
[Issue]: new artemis build and warp 2 bug.

### ISSUE THREAD

**Issue by Killboywes** [ClassicOldSong/moonlight-android#374]
### Describe the bug

The new Artemis build is absolutely insane — running on a 7800X3D, RTX 4090, and Galaxy S24 Ultra (Snapdragon Gen 3). I also enabled double Hz mode (otherwise the FPS client would drop) — something I discussed with you earlier, and you implemented it perfectly. And running av1

On my previous setup, I was getting 2.3–3.5 ms decoding latency with Balanced Frame Pacing enabled and Ultra Low Latency disabled (since enabling it actually added latency).

With the new build, latency is now down to 1.2–1.5 ms on the same settings. (Ultra Low Latency still results in slightly higher latency on the S24 Ultra.)

And with Warp 2, latency drops even further to 0.60–0.80 ms. The only issue: FPS fluctuates between 115–120 FPS, which makes the output look jittery/stuttery.
Any idea what could be causing this?

### Steps to reproduce

No

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

No

### Android version

15

### Device model

S24 ultra 

### Server PC OS version

W11 23h2

### Relevant log output

```Shell

```

**Comment by ClassicOldSong** [comment]
These options are pushing the limit of your device, so don't expect them to "magically" work without compromises.

**Comment by Killboywes** [comment]
> These options are pushing the limit of your device, so don't expect them to "magically" work without compromises.

So warp 2 can push the limits that's why it can looks jittery?  Then I keep using balanced, still I don't know how you did it but even with ultra low agency off and balanced mode decoding latency is halved!

**Comment by Killboywes** [comment]
A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!

Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!

Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.

**Comment by ClassicOldSong** [comment]
Yes, Warp 2 was done by me as a hack for lower latency. It wasn't this bad before as the new options pushes the limit further.

The new options are done by @derflacco , who have implemented the thing I thought was unnecessary. In short, a buffer is necessary for smooth playback, but the new options just tries to bypass the buffer to provide the lowest latency possible. So any fluctations in the network or elsewhere can lead to more dropped frames. But if you're on a good network, it does get lower latency without losting too much frames.

**Comment by ClassicOldSong** [comment]
You should disable ForceTightThresholds if your decoding latency is already low. This can cause more stutters.

**Comment by Killboywes** [comment]
> You should disable ForceTightThresholds if your decoding latency is already low. This can cause more stutters.

In apollo self in video or where should that option be,

But what did you do that even makes the decoding time drop by a lot without even warp 2 ultra low latency and latest frame rendering haha. It's amazing

**Comment by ClassicOldSong** [comment]
ForceTightThresholds is another newly added option in Artemis

**Comment by Killboywes** [comment]
> ForceTightThresholds is another newly added option in Artemis

It was already not checked,

Holy shit 

I did test the new artemis on my TV omx, mtk

And decoding latency went from 11 to 8.5, did you even tweaked more?  Because on all my devices decoding latency went down even with Al those settings disabled and ultra low latency disabled.

**Comment by ClassicOldSong** [comment]
All thses you should thank @derflacco

**Comment by Killboywes** [comment]
> All thses you should thank [@derflacco](https://github.com/derflacco)

So even without ultra low latency. Warp 2 mode, and the other 2 new options some of his fixes are in the build itself also without all those settings enabled? That lowers the decoding times

**Comment by ClassicOldSong** [comment]
Yes, but ultra low latency is still recommended to be enabled on supported devices

**Comment by Killboywes** [comment]
> Yes, but ultra low latency is still recommended to be enabled on supported devices

Insane, sadly ultra low latency does the opposite on my s24 ultra, it gives me higher latency that's weird for the snap 8 gen 3.

Happy and grateful with al you're hard work and the contribution of all people. I helped so many friend switch from sunshine and moonlight to Apollo and artemis with double refresh rate it fixed al their problems. Amd and 'nvdia build

**Comment by ClassicOldSong** [comment]
Weird, only with ultra low latency I can reach 1ms decoding time on my 8sGen3, which shares the same decoding circurt of 8Gen3...

**Comment by Killboywes** [comment]
> Weird, only with ultra low latency I can reach 1ms decoding time on my 8sGen3, which shares the same decoding circurt of 8Gen3...

That's weird, maybe bause the snapdragon 8 gen 3 in samsung are overclocked by samsung so they react different with the ultra low latency setting?

I'm getting 0.60 decoding time with warp 2 and ultra low latency disabled. And 1.2ms decoding with balanced/smoothest video  frame pacing 

So I keep using balanced/prefer smoothes video probably because it looks more fluently

**Comment by VirtualGIT20** [comment]
> A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> 
> Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> 
> Gonna test my other TV with a mtx decoder and gonna update you in a few minutes. 


Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily

**Comment by derflacco** [comment]
> > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> 
> Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily

Try this:
https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental

Tweaks:
https://github.com/derflacco/moonlight-android/commits/experimental/

**Comment by VirtualGIT20** [comment]
> > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > 
> > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> 
> Try this:
> https://fromsmash.com/send
> 
> Tweaks:
> https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e
> 

Sorry, the link you sent give error 404

**Comment by derflacco** [comment]
> > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > 
> > > 
> > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > 
> > 
> > Try this:
> > https://fromsmash.com/send
> > Tweaks:
> > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> 
> Sorry, the link you sent give error 404

Try now with the new one:
https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental

**Comment by VirtualGIT20** [comment]
> > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > 
> > > > 
> > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > 
> > > 
> > > Try this:
> > > https://fromsmash.com/send
> > > Tweaks:
> > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > 
> > Sorry, the link you sent give error 404
> 
> Try now with the new one:
> https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental

Tested the version you provided. Here are my findings:

Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled. 

- I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.

- Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.

I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues.
With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.

Let me know if I can help you with some logs or something.

**Comment by derflacco** [comment]
> > > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > > 
> > > > > 
> > > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > > 
> > > > 
> > > > Try this:
> > > > https://fromsmash.com/send
> > > > Tweaks:
> > > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > > 
> > > 
> > > Sorry, the link you sent give error 404
> > 
> > 
> > Try now with the new one:
> > https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental
> 
> Tested the version you provided. Here are my findings:
> 
> Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled.
> 
> * I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
>   Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.
> * Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.
> 
> I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues. With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.
> 
> Let me know if I can help you with some logs or something.


another one

sources:https://github.com/derflacco/moonlight-android/commits/experimental/

**Comment by Killboywes** [comment]
> > > > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > > > 
> > > > > > 
> > > > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > > > 
> > > > > 
> > > > > Try this:
> > > > > https://fromsmash.com/send
> > > > > Tweaks:
> > > > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > > > 
> > > > 
> > > > Sorry, the link you sent give error 404
> > > 
> > > 
> > > Try now with the new one:
> > > https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental
> > 
> > 
> > Tested the version you provided. Here are my findings:
> > Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled.
> > 
> > * I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
> >   Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.
> > * Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.
> > 
> > I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues. With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.
> > Let me know if I can help you with some logs or something.
> 
> https://fromsmash.com/tegra-exp another one
> 
> sources:https://github.com/derflacco/moonlight-android/commits/experimental/

Please don't remove the lower latency on the shield, for me it works great on my shield and my latency dropped from 2ms to 0.22 to 0.88 ms at 300mb bitrate 4k on wifi no problem or packet loss it runs smooth as hell. 

Running double refresh rate  in apollo and balanced or smoothest video frame pacing  I experience 0 stutters or jitter

**Comment by Killboywes** [comment]
> Yes, but ultra low latency is still recommended to be enabled on supported devices

I think I found out why warp 2 modes looks bad on my s24 ultra, I enabled gpu watch in developer options, and for some reason warp 2 makes artemis running at 60 fps. (refresh rate still at 120 rock solid) when I change to a different frame pacing it goes back to 120 fps with goh watch.

**Comment by Killboywes** [comment]
> > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> 
> Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily

Do you have double refresh rate enabled in apollo? And cap fps to 60 with rtss? 
This fixed all my fps drops on all my clients and more people and friends.

**Comment by VirtualGIT20** [comment]
> > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > 
> > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> 
> Do you have double refresh rate enabled in apollo? And cap fps to 60 with rtss? 
> This fixed all my fps drops on all my clients and more people and friends. 

I confirm that I'm already using those settings for the previous version, tested also with the double refresh rate option disabled without any noticeable difference.

For fps limiter, I'm using the RTSS one with Reflex, tested also async but no difference.

The only difference in my configuration from what you have shared is 150mbps bitrate and 1440p resolution.

**Comment by VirtualGIT20** [comment]
> > > > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > > > 
> > > > > > 
> > > > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > > > 
> > > > > 
> > > > > Try this:
> > > > > https://fromsmash.com/send
> > > > > Tweaks:
> > > > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > > > 
> > > > 
> > > > Sorry, the link you sent give error 404
> > > 
> > > 
> > > Try now with the new one:
> > > https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental
> > 
> > Tested the version you provided. Here are my findings:
> > 
> > Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled.
> > 
> > * I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
> >   Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.
> > * Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.
> > 
> > I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues. With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.
> > 
> > Let me know if I can help you with some logs or something.
> 
> 
> another one
> 
> sources:https://github.com/derflacco/moonlight-android/commits/experimental/

Tested the second version provided in the link, no noticeable difference from the previous test version.
I can send you a video if you want for further testing (latency stats will be in Italian, but I think it shouldn't be a problem) 

EDIT:
Did some further testing, I had to unistall the previous experimental version to see the difference with the latest one.

This one behaves similarly to the prerelease, low decoding latency even with the new settings disabled, occasional stuttering after a minute or two of playing.

**Comment by Killboywes** [comment]
> > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > 
> > > 
> > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > 
> > 
> > Do you have double refresh rate enabled in apollo? And cap fps to 60 with rtss?
> > This fixed all my fps drops on all my clients and more people and friends.
> 
> I confirm that I'm already using those settings for the previous version, tested also with the double refresh rate option disabled without any noticeable difference.
> 
> For fps limiter, I'm using the RTSS one with Reflex, tested also async but no difference.
> 
> The only difference in my configuration from what you have shared is 150mbps bitrate and 1440p resolution.

And reverting back to older artemis fixed it?

**Comment by VirtualGIT20** [comment]
> > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > 
> > > > 
> > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > 
> > > 
> > > Do you have double refresh rate enabled in apollo? And cap fps to 60 with rtss?
> > > This fixed all my fps drops on all my clients and more people and friends.
> > 
> > 
> > I confirm that I'm already using those settings for the previous version, tested also with the double refresh rate option disabled without any noticeable difference.
> > For fps limiter, I'm using the RTSS one with Reflex, tested also async but no difference.
> > The only difference in my configuration from what you have shared is 150mbps bitrate and 1440p resolution.
> 
> And reverting back to older artemis fixed it?

That's correct.

With the latest experimental version shared by @derflacco , I can easily switch between versions and the "older" one is consistently stable (with "smoothest" framepacing).

I've also noted that in the old one input and rendered frames always match, while in the prerelease  sometimes the rendered one's are lower or even higher than the input frames.

**Comment by derflacco** [comment]
> > > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > > 
> > > > > 
> > > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > > 
> > > > 
> > > > Try this:
> > > > https://fromsmash.com/send
> > > > Tweaks:
> > > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > > 
> > > 
> > > Sorry, the link you sent give error 404
> > 
> > 
> > Try now with the new one:
> > https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental
> 
> Tested the version you provided. Here are my findings:
> 
> Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled.
> 
> * I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
>   Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.
> * Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.
> 
> I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues. With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.
> 
> Let me know if I can help you with some logs or something.

I think I’ve fixed it. The issue came from a commit I added to stabilize rendering on slower devices, but it ended up causing severe packet loss. I’ve also removed the gating of the latest-only low latency path on NVIDIA decoders. Please test."
https://fromsmash.com/tregratest

**Comment by Killboywes** [comment]
> > > > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > > > 
> > > > > > 
> > > > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > > > 
> > > > > 
> > > > > Try this:
> > > > > https://fromsmash.com/send
> > > > > Tweaks:
> > > > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > > > 
> > > > 
> > > > Sorry, the link you sent give error 404
> > > 
> > > 
> > > Try now with the new one:
> > > https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental
> > 
> > 
> > Tested the version you provided. Here are my findings:
> > Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled.
> > 
> > * I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
> >   Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.
> > * Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.
> > 
> > I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues. With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.
> > Let me know if I can help you with some logs or something.
> 
> I think I’ve fixed it. The issue came from a commit I added to stabilize rendering on slower devices, but it ended up causing severe packet loss. I’ve also removed the gating of the latest-only low latency path on NVIDIA decoders. Please test." https://fromsmash.com/tregratest

Does this mean the decoding time is higher like before on the shield? I hope not I'm liking the 0.2 to 0.8 decoding time

For me an some more people I have seen on reddit the alpha artemis build works great in their shield.

**Comment by derflacco** [comment]
> > > > > > > > A Quick update I also installed it on my shield, it's running smoothest video, and the new latest frame rendering, and the decoding latency also decreased a lot!
> > > > > > > > Went from 1.8 to 3ms to 0.22 and 1.8ms what in the heaven have you done it's insane!
> > > > > > > > Gonna test my other TV with a mtx decoder and gonna update you in a few minutes.
> > > > > > > 
> > > > > > > 
> > > > > > > Did you manage to find a setting configuration that doesn't drop frames? In my shield, even with all the new option disabled, after like 30 seconds in begin to stutter heavily
> > > > > > 
> > > > > > 
> > > > > > Try this:
> > > > > > https://fromsmash.com/send
> > > > > > Tweaks:
> > > > > > [derflacco@f90333c](https://github.com/derflacco/moonlight-android/commit/f90333ccc819e2f5166fe736b63ae5d559e8499e)
> > > > > 
> > > > > 
> > > > > Sorry, the link you sent give error 404
> > > > 
> > > > 
> > > > Try now with the new one:
> > > > https://fromsmash.com/DianaNvidiaTegraQcomC2Experimental
> > > 
> > > 
> > > Tested the version you provided. Here are my findings:
> > > Tried all frame pacing options (Low Latency, Balanced, Smoothest) with all new settings disabled.
> > > 
> > > * I’m consistently getting fewer rendered frames than input frames (e.g., 60 input → 49–55 rendered).
> > >   Decoding times stay between 0.50–2 ms, which is similar to the latest prerelease.
> > > * Enabling Ultra Low Latency, Latest Frame Rendering, or Tight VSync shows similar behavior—no improvement in frame rendering.
> > > 
> > > I also had to lower the bitrate significantly compared to the previous version. On the last version, I was using 150 Mbps without issues. With this build, ~90% of packets drop at 150 Mbps, so I tested at 40 Mbps instead.
> > > Let me know if I can help you with some logs or something.
> > 
> > 
> > I think I’ve fixed it. The issue came from a commit I added to stabilize rendering on slower devices, but it ended up causing severe packet loss. I’ve also removed the gating of the latest-only low latency path on NVIDIA decoders. Please test." https://fromsmash.com/tregratest
> 
> Does this mean the decoding time is higher like before on the shield? I hope not I'm liking the 0.2 to 0.8 decoding time
> 
> For me an some more people I have seen on reddit the alpha artemis build works great in their shield.

No, if you refer to this commit:
https://github.com/derflacco/moonlight-android/commit/53c652de2e643b3c47bee12c532d2bee2a3ff8f0
That commit re-enables the low-latency path on NVIDIA decoders, which had previously been disabled.

**Comment by bernhardberger** [comment]
Not sure where else to post this since this has become what seems to be a general discussion of the experimental build - but the new experimental build fixes ally ossues I had on my Bravia 8 (XR80) TV (Mediatek device). 

Buttery smooth 4k60 HDR at 200mbit HEVC at 2-4ms latency.

It was unusable before (stuttering, vsync problems, microfreezes at every vsync interval 20+ms decoding times), now it's actually a viable option on Bravia TVs!

Kudos @derflacco and @ClassicOldSong this is looking very promising for MTK devices that were hella buggy before!

**Comment by VirtualGIT20** [comment]
> 
> I think I’ve fixed it. The issue came from a commit I added to stabilize rendering on slower devices, but it ended up causing severe packet loss. I’ve also removed the gating of the latest-only low latency path on NVIDIA decoders. Please test."
> https://fromsmash.com/tregratest

Hi

Did some testing with this version, but seems like the issue regarding the severe packet loss is still present and behaving like before.
Just to be sure, I've unistalled the previous version, cleaned cache and re-downloaded this one but it's behaving the same.

**Comment by ClassicOldSong** [comment]
Well for newer conversations you can quote only the necessary lines...

Each reply is getting way too clumsy at the moment

**Comment by VirtualGIT20** [comment]
> > I think I’ve fixed it. The issue came from a commit I added to stabilize rendering on slower devices, but it ended up causing severe packet loss. I’ve also removed the gating of the latest-only low latency path on NVIDIA decoders. Please test."
> > https://fromsmash.com/tregratest
> 
> Hi
> 
> Did some testing with this version, but seems like the issue regarding the severe packet loss is still present and behaving like before.
> Just to be sure, I've unistalled the previous version, cleaned cache and re-downloaded this one but it's behaving the same.

**Comment by Killboywes** [comment]
> > 
> No, if you refer to this commit: [derflacco@53c652d](https://github.com/derflacco/moonlight-android/commit/53c652de2e643b3c47bee12c532d2bee2a3ff8f0) That commit re-enables the low-latency path on NVIDIA decoders, which had previously been disabled.

Okay so the new build still has the same low latency on 'nvdia shield :)?

**Comment by BatJoe** [comment]
For nVidia Shield Pro users, is Latest Frame Rendering & Tight VSync recommended to enable or disable?
