### ISSUE TITLE
[Issue]: Multitouch/pen/touch mode stutter

### ISSUE THREAD

**Issue by stevenxed** [ClassicOldSong/moonlight-android#384]
### Describe the bug

The multitouch mode stutters heavily for a few seconds at a time at random intervals (usually every few minutes) easily noticeable when scrolling around on the touchscreen. Scrolling with the actual mouse is smooth during these stutters so the stream itself is unlikely the issue. It happens in all applications and doesn't seem dependent on cpu/gpu load. It's been like this ever since I started using multitouch.

This looks to be the same exact issue in the moonlight repo: moonlight-stream/moonlight-android#1427

### Steps to reproduce

Enable multitouch mode and just scroll around for a few minutes on the touchscreen.

None of the settings in Artemis or Apollo seem to fix it.

### Affected games

Any application

### Other Moonlight clients

None

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

1920x1080@120.04
Prefer lowest latency
Latest-Frame Rendering (Experimental) On
Ultra Low Latency (experimental) On
Tight Vsync (Experimental) On
Default touchscreen mode = Multitouch
Some OSD settings.

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

Yes

### Android version

Android 16

### Device model

Google Pixel 9 Pro

### Server PC OS version

Windows 11 25H2

### Server PC GeForce Experience version

11.0.5.245

### Server PC Nvidia GPU driver version

581.15

### Server PC antivirus and firewall software

Windows Defender and Windows Firewall

### Screenshots

Reference the issue I posted above.

### Relevant log output

```Shell

```

**Comment by ClassicOldSong** [comment]
1. Disable controller battery status report

2. Enable Prevent Packet Loss (need the latest pre release)

**Comment by stevenxed** [comment]
Oh I didn't know about the battery report option. I'll report back if this fixes it, thanks!

**Comment by ClassicOldSong** [comment]
This is one of the very first problems fixed with Artemis and I never met it once after that. Tested on multiple devices with pen support.

**Comment by stevenxed** [comment]
Ok it just happened, do I need to quit the app in artemis and start it again to apply that change?

**Comment by ClassicOldSong** [comment]
It shouldn't, but you can try

Make sure you're editing the settings of your current profile 

What device do you have?

**Comment by stevenxed** [comment]
Yeah I just tried and it still happens. I haven't set up any profiles so it should've applied.

A windows 11 desktop and a Pixel 9 pro.

Recorded a short clip of it with OBS and I scrolled using just my phone. Oh and attempted to scroll with the mouse after the second stutter.
https://github.com/user-attachments/assets/3720db7f-49ce-4787-8fb0-229d8fbef0b0

**Comment by ClassicOldSong** [comment]
Weird, but I don't think disabling batching is the way to fix this problem

Have you tried on different clients device? We need to isolate where the problem actually occurs

**Comment by stevenxed** [comment]
I have not and it'll be a day or two till I can test on another android device so i'll update you then.

**Comment by testerl101** [comment]
This is not directly related to this but i have come from the stylus issues thread. I am using an ipad pro as wireless connection to my pc, and although i dont have random intervals of lag, my cursors repeatedly lags in the begining of each stroke, everytime. Not only does that with a stylus, but just touch control too. Any ideas what could be causing this?

EDIT: disabeling native pen support also had no effect whatsoever.

**Comment by testerl101** [comment]
UPDATE: so this was cause due to touchscreen mode. For some reason touchscreen mode messes with the input data. After switching to toupad mode, the stylus began working normally, although hovering the stylus glitches windows into fast switching between ink mode and normal mode.

I tried this on my Xiaomi pad 5 too, and that had no issues in any modes, plus stylus hover worked normally. I suspect this is due to moonlight app as it is different than the android one, shame its this buggy on the ipad.

**Comment by stevenxed** [comment]
Just tested with a lower spec'd Samsung A42 5G and it did not have the bug.

I started the stream with the same 1080 resolution but at 60hz instead of the usual 120 from the pixel.
Had both phones connected to the stream/app on the same aretmis build (v20.3.0-experimental.4), same exact settings enabled (all the new experimental features, packet loss fix, and the battery report off), 60hz/hevc decoding.
The moment the pixel stutters, I switch to the samsung and it was smooth. Went back and forth like that a few times with the same results until it disappeared on the pixel.
Tried streaming with just the pixel at the same settings, same result. Tried streaming with just the samsung and it stayed smooth.

**Comment by ClassicOldSong** [comment]
So it's another Pixel only problem I guess, but unfortunately I don't have Pixel devices to test with so it's hard to pinpoint the exact issue

**Comment by stevenxed** [comment]
Anything I can do to help?

**Comment by Snowflakesy** [comment]
I am using a Galaxy Tab S10 Ultra, streaming to Linux Mint, and experienced the same problem. The pre-release option to prevent packet loss fixed it for me.

Edit 16. Mai. 2026

I am now on Arch Linux. Prevent packet loss does not fix it for me anymore.

**Comment by 0hite** [comment]
Happens on tab S11 with windows artemis apollo setup. Prevent packet loss didnt fix it

**Comment by SproedKartoffelChip** [comment]
Tab S11, Ubuntu Linux setup, happens here on KDE Plasma as well.

**Comment by FlySlime** [comment]
Tab S11 also having this issue on KDE Plasma Arch Linux. Packet loss did not fix either nor did setting touchscreen mode to disabled

**Comment by notlccc** [comment]
**重磅突破**（可能是）

该问题极有可能是高通 fastconnect 6900 的锅。我在骁龙 8+ gen 1（以下简称 8p ）设备上串流时会遇到类似问题，而切换至骁龙 8 gen 2（以下简称 8g2 ）及以上骁龙 soc 设备则不会遇到此类问题

以上状况并不能完全证明是高通的锅，但我的笔记本使用了 QCNFA765 无线网卡（以下简称765），使用的正是高通 fastconnect 6900 平台

我手头还有一台骁龙 8 elite 设备（以下简称 8e）、两块联发科无线网卡（MT7922 和 MT7925，以下简称 22 和 25）以及一个电脑网线直连的 wifi6 路由器，于是有了以下组合方式和问题是否可以复现的关系：

22 + 8p = 复现
765 + 8p = 复现，**且频率更高**
路由器 + 8p = 复现
**路由器 + 8g2 = 正常**

混乱的测试进行到这个阶段，我就模糊地认为是 8p 的问题，于是开始使用 8e 的设备

路由器 + 8e = 正常
25 = 8e = 正常
**765 + 8e = 竟然又复现了**

如果真是 fastconnect 6900 的锅，那么也就可以解释为什么 765 + 8p 这个组合问题出现的频率更高了

所以我认为结果就是本来我以为同平台的网络设备可以提升我的使用体验，但其实主要就是这个无线平台的问题导致了此类卡顿，我*还没有检查其它类似 issue 是否都是此类平台的*，不过我想这至少也可以作为解决此类问题的一个突破点了。
